### ISSUE TITLE
Document: "Check Linked Containers" config setting

### ISSUE THREAD

**Issue by grrowl** [buildkite-plugins/docker-compose-buildkite-plugin#105]
Please document how config option `CHECK_LINKED_CONTAINERS` (aka env `BUILDKITE_PLUGIN_DOCKER_COMPOSE_CHECK_LINKED_CONTAINERS`) should be used, as seen in https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/hooks/commands/run.sh#L98

I've tried defining the env var in `pipeline.yml` (in top-level key `env` and in `steps.command.plugins.docker-compose#v1.8.3.env`) but each seemed to have no effect.

**Comment by grrowl** [comment]
Specifically we have two containers in our compose — selenium/hub and and selenium/node-chrome — who log to stdout and which we need the output for (to debug selenium, natch)

We're successful collecting log artifacts from containers which write to files in mapped volumes; but I can't find a solution for these selenium-based ones which only write to stdout

**Comment by lox** [comment]
The "check linked containers" setting is supposed to be the default behaviour, which in the case of a failure should grab the log output from all linked containers and upload the logs as assets. 

We've just fixed a bug that stopped this behaviour from running (see #103), which I suspect you might be running into.

Beyond that, we've been talking about ways to show logging from all linked containers in #98.

I'm going to get out a new release in the next few minutes @grrowl, hopefully it should fix the issue for you until we have a good solution to showing log output from multiple containers.

**Comment by grrowl** [comment]
Glorious, thank you! I'll test imminently and follow up

**Comment by grrowl** [comment]
Confirmed `docker-compose#v1.8.4` fixes the issue. Each composed container's logs are uploaded as artifacts, and the main app's log is output in the Buildkite UI.

Thanks for the excellent and speedy reply @lox!
