### ISSUE TITLE
Force updated images to be pulled

### ISSUE THREAD

**Issue by gazzer82** [buildkite-plugins/docker-compose-buildkite-plugin#115]
Is their any way to force the plugin to always pull a fresh version of a pre-built image, I would normally do a docker-compose pull locally but I don't have the option of doing that here?

**Comment by lox** [comment]
Each step should pull down a pre-built image built in a previous step, are you seeing different behaviour @gazzer82?

**Comment by grrowl** [comment]
some of our `docker-compose`s have dependent services which should always be fresh. For example, our integration tests can be triggered from API or Web pipelines. When triggered from the API pipeline, it will use web's `:develop-latest`, but it should pull it on every run.

**Comment by pecigonzalo** [comment]
I think this might have been related to ensuring you pull other images, maybe doing a `docker-compose -f [...] pull` before doing a run.
This is important when you have other images you are also using (postgres, etc) and you want to ensure latest is pulled.

**Comment by rafaelmagu** [comment]
We also ran into this issue recently: a dependent service in the Compose file is using a stale image from the cache.
