### ISSUE TITLE
Don't dump all container logs to the main output

### ISSUE THREAD

**Issue by grrowl** [buildkite-plugins/docker-compose-buildkite-plugin#138]
`docker-compose` logs are uploaded as artifacts (as `docker-compose-logs/<container id>.log` files), but it's also dumped en masse to the main log. It'd be great to have the `docker-compose-logs` artifacts be named (or suffixed with the name), and avoid having those logs dumped out into the main log.

I'm aware there may be issues with some logs not uploading, or possibly that naming the docker-compose logs might not be possible. Hoping filing this issue will open some discussion, since our integration tests tend to error in the main container (and hence in the main logs) but it's significantly harder to debug a >1MB log with irrelevant output from selenium, chrome, rails db:seed output, etc.

**Comment by lox** [comment]
I think the fact that the main container output gets written as a log file and uploaded on error is probably a bug.
