### ISSUE TITLE
How does image-repository get authenticated?

### ISSUE THREAD

**Issue by benschwarz** [buildkite-plugins/docker-compose-buildkite-plugin#145]
[The readme](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin#image-repository-optional-build-only) mentions image-repository and explains to enter a string name reference to the repo. 👍 

I've some questions (Framed around the idea of using them to improve the readme):
- How does the docker image pull/push get authenticated? 
- Where should that information be stored? 
- Is it secure? 
- Should it be used for private projects? Is it a recommended thing to do? 
- Is this a best practice? Do you want to encourage people to do this?

**Comment by toolmantim** [comment]
Thanks! I've just updated our docs in a087627 to try to answer all these questions.
