### ISSUE TITLE
Clean up tags in the teardown?

### ISSUE THREAD

**Issue by lox** [buildkite-plugins/docker-compose-buildkite-plugin#15]
Should this plugin clear out it's docker tags once done? ECR has a 1000 image limit and this will result in hitting it quickly.

**Comment by piotrb** [comment]
I ended up creating a little lambda that does this for me .. but yea automatic cleanup would be nice .. although you're need like a teardown step in  the pipeline that runs regardless of the pipeline failing

**Comment by lox** [comment]
@piotrb

**Comment by lox** [comment]
Sorry about that, finger slipped :)

**Comment by lox** [comment]
Given ECR has a solution for this now, I'm going to close this.
