### ISSUE TITLE
Build step for fails for docker-compose service with a dash in the name

### ISSUE THREAD

**Issue by reidab** [buildkite-plugins/docker-compose-buildkite-plugin#151]
Running a build step for a docker-compose service with the name `fastboot-server` fails with:

```
[...]/commands/build.sh: line 35: cache_from__fastboot-server: bad substitution
``` 

Renaming that docker-compose service to `fastboot` works fine.

**Comment by toolmantim** [comment]
This is fixed in [v2.5.1 (🛁 Bath Time)](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/releases/tag/v2.5.1)
