### ISSUE TITLE
'Cannot overwrite digest' errors when pulling images in a multi agent node

### ISSUE THREAD

**Issue by arturopie** [buildkite-plugins/docker-compose-buildkite-plugin#162]
We run 8 agents per machine, and when they all try to pull the image at the same time, some agents fail with a `Cannot overwrite digest` error. Here is an example of the error:

```

$ docker-compose -f docker/docker-compose-test.yml -p buildkited11ad3edc2274fddb73c4449d24367ba -f docker-compose.buildkite-7180-override.yml pull pm_test
--
  | Pulling pm_test ...
  |  
  | ERROR: for pm_test  Cannot overwrite digest sha256:817f2f16a7c65a01c356e50d42f7111c5c2bc98163ceef17b7f34b69c05c4e8e
  | ERROR: Cannot overwrite digest sha256:817f2f16a7c65a01c356e50d42f7111c5c2bc98163ceef17b7f34b69c05c4e8e
  | Exited with 1

```

I imagine having the plugin using an flock could solve this problem. Thoughts?

**Comment by toolmantim** [comment]
This doesn't sound good, sorry you hit that.

I wonder if this is a problem in Docker itself… those error messages don't sound like they're generated from Docker Compose.

**Comment by arturopie** [comment]
yes, it's a problem that could be solved in docker, and this plugin could also implement a solution to this problem since this is probably affecting other buildkite users.

**Comment by toolmantim** [comment]
Where is the digest coming from? Could you share more details, like the relevant parts of the Dockerfile, docker-compose.yml, and the Docker and Docker Compose versions?

**Comment by arturopie** [comment]
I believe that's the digest for the docker image. Here is more output when it failed

```
Creating network "buildkitedb3de6eb3d5449328230b1cfc899af0d_default" with the default driver
--
  | Pulling pm_postgres_test (postgres:9.3.9)...
  | 9.3.9: Pulling from library/postgres
  | f8efbffe7b95: Pull complete
  | a3ed95caeb02: Pull complete
  | 64bb2775d20d: Pull complete
  | 112aae0540bb: Pull complete
  | 96d2a7a4fcb3: Pull complete
  | 8d43a1a2d52b: Pull complete
  | 1eba7ded6f54: Pull complete
  | 72377f1d0630: Pull complete
  | fc6482301aed: Pull complete
  | ee492f1ecff9: Pull complete
  | b2f4643ef27e: Pull complete
  | 793d7d756766: Pull complete
  | Digest: sha256:ce0787961e340e6660f7039cbcb2a4588caa1b6f36a748905249c365da9d88ed
  | ERROR: Cannot overwrite digest sha256:ce0787961e340e6660f7039cbcb2a4588caa1b6f36a748905249c365da9d88ed
  |   | ⚠️ Failed to run command, exited with 1
```

And here is the output of an agent in the same machine that successfully pulled the image:

```
Creating network "buildkited5538da4c97741fab64b69f05b4c7f4a_default" with the default driver
--
  | Pulling pm_postgres_test (postgres:9.3.9)...
  | 9.3.9: Pulling from library/postgres
  | f8efbffe7b95: Pull complete
  | a3ed95caeb02: Pull complete
  | 64bb2775d20d: Pull complete
  | 112aae0540bb: Pull complete
  | 96d2a7a4fcb3: Pull complete
  | 8d43a1a2d52b: Pull complete
  | 1eba7ded6f54: Pull complete
  | 72377f1d0630: Pull complete
  | fc6482301aed: Pull complete
  | ee492f1ecff9: Pull complete
  | b2f4643ef27e: Pull complete
  | 793d7d756766: Pull complete
  | Digest: sha256:ce0787961e340e6660f7039cbcb2a4588caa1b6f36a748905249c365da9d88ed
  | Status: Downloaded newer image for postgres:9.3.9
```
Here is the relevant part of the docker-compose file:

```
  pm_postgres_test:
    image: postgres:9.3.9
    expose:
      - "5432"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
```

Docker version: 18.03.0-ce
Docker ompose version: 2.5.1
BUILDKITE_STACK_VERSION=v3.2.1
BUILDKITE_AGENTS_PER_INSTANCE=8

**Comment by lox** [comment]
I've seen this before, it's a docker race condition around concurrent pulls on the same image. I had a quick look for the open issue and couldn't find it, are you in a position to upgrade to a newer stack @arturopie?

**Comment by arturopie** [comment]
@lox I tested 4.0.0-rc1, and it seems to work fine. We are waiting for the release of the stable version to upgrade our main CI pipeline

**Comment by lox** [comment]
I'm going to close this one for now, as it should be addressed by a docker version update. Even if it isn't I think I'd be reluctant to add per-host synchronization of pulls into this plugin, but lets cross that bridge if the error crops up again!
