### ISSUE TITLE
Canceled jobs don't clean up networks

### ISSUE THREAD

**Issue by jdotjdot** [buildkite-plugins/docker-compose-buildkite-plugin#169]
We've discovered that currently running jobs using this plugin, when canceled, clean up their containers but don't clean up the networks that were created.  They *are* cleaned up when the job runs successfully.

This has resulted in our build server repeatedly breaking due to no IP space being left.

**Comment by praveensastry** [comment]
@jdotjdot we had similar issue as well, but as a workaround we created a pre-exit hook and deleted the  networks using a script

```
DOCKER_NETWORKS=$(docker network ls -f "name=buildkite${BUILDKITE_JOB_ID//-}" -q)
if [ -n "$DOCKER_NETWORKS" ]; then
  docker network rm $DOCKER_NETWORKS
fi
```

**Comment by lox** [comment]
Sorry about that @jdotjdot / @praveensastry. Currently this plugin is executed as a single command hook, so if it's cancelled it will be interrupted and not do the cleanup.

I think it would make a lot of sense to move the cleanup to a `pre-exit`, along the lines of what @praveensastry did above, as the `pre-exit` will be run on cancel.
