### ISSUE TITLE
Ability to specify the local directory to mount (Monorepo support).

### ISSUE THREAD

**Issue by grahamegee** [buildkite-plugins/docker-compose-buildkite-plugin#173]
I have a monorepo with roughly the following structure.

* shared libraries
   * library 1 ...
* services
   * service 1 ...
      * Dockerfile

Currently because our shared libraries aren't stable enough to package up we need to copy them in during docker build, i.e. our docker build context needs to be the root of the repository, so one of the current suggestions for monorepo support detailed here https://github.com/buildkite/feedback/issues/405 (tl;dr change directory to the relevant service within a hook) won't work for us. 

In order to run tests using the plugin for individual services I need to be able to mount in only the specific service directory. Default behaviour mounts in the root directory and therefore the test runners can't find the tests.

**Comment by lox** [comment]
Currently this plugin doesn't do any sort of mounting of directories I don't think! 

Am I understanding you correctly that you want to be able to specify a specific sub-directory of your checkout to mount into one of the services in your docker-compose.yml file? I suspect that might be best suited for another plugin or a `pre-command` hook that changes the working directory, and then using relative paths in your `docker-compose.yml`.

I'm going to close this one for now, please let me know if I've misunderstood and I'll re-open.
