### ISSUE TITLE
remove reference to cleanup config flag

### ISSUE THREAD

**Issue by nhooyr** [buildkite-plugins/docker-compose-buildkite-plugin#199]
See https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/61cc42d2195853ed3dc8cb0a68b1f05b440818cc/hooks/pre-exit#L13

> plugin_read_config CLEANUP "true"

There is no cleanup flag and therefore that comparison is always true.

**Comment by toolmantim** [comment]
This is somewhat of a hack used in the unit tests only, because it’s a tricky one to test for. If you manage to figure out a cleaner approach, would be more than welcome to accept a change.
