### ISSUE TITLE
Option for upload all service logs

### ISSUE THREAD

**Issue by pecigonzalo** [buildkite-plugins/docker-compose-buildkite-plugin#206]
The PR #196 introduced some other changes than the ones described but one of them I believe should be reverted.
```
service_exit_code="$(docker inspect --format='{{.State.ExitCode}}' "$service_container_id")"

# Capture logs if the linked container failed
if [[ "$service_exit_code" -ne 0 ]] ; then
```

Makes it so only the failed container logs are uploaded, which I don't believe is the desired default behavior. Most compose groups, might have a failure in 1 container, due to something that happened in another, that did not fail.
EG: You get a 401 in a curl test, but you actually need the NGINX logs to better understand what happened.

I would propose to add: https://github.com/pecigonzalo/docker-compose-buildkite-plugin/tree/feature/log-options

**Comment by RootTJNII** [comment]
+1.  I have a failing test where microservices run in multiple containers and the plugin runs a test runner container.  There is a problem with one of the microservices but I now can't see the log.  I agree with @pecigonzalo that the logs of all the containers should be uploaded, for the same reason, and that this behavior change was unexpected and not desirable in our environment.

**Comment by toote** [comment]
It would appear that PR #210 implemented the exact functionality necessary. Closing
