### ISSUE TITLE
Feature request: Configure `userns_mode`

### ISSUE THREAD

**Issue by s01ipsist** [buildkite-plugins/docker-compose-buildkite-plugin#209]
As a user with an elastic ci stack with docker user namespace enabled (the default for `EnableDockerUserNamespaceRemap`), I would like to disable, or otherwise configure, the user namespace for a particular build step running with this plugin by configuring the `userns_mode` docker compose parameter.

https://docs.docker.com/compose/compose-file/#userns_mode
https://docs.docker.com/engine/security/userns-remap/

**Comment by toolmantim** [comment]
I'm not sure if you could reconfigure the elastic CI stack’s `EnableDockerUserNamespaceRemap` from this plugin? Perhaps @lox might know better how these two interact?

**Comment by s01ipsist** [comment]
As I understand `EnableDockerUserNamespaceRemap` would configure the "server" default, but setting `userns_mode` would override for any particular run.

**Comment by lox** [comment]
That's correct @s01ipsist, I do recall someone mentioning they didn't have much luck trying to disable it on a per-run basis 🤔

**Comment by s01ipsist** [comment]
I can understand if you didn't want to add a feature that may or may not work as documented. Would you consider an alternative approach where an `--extra-args` or similar allowed direct pass through of arguments. It's an "extra for experts" feature and somewhat future-proofs the plugin in that it allows users to adopt new features before the plugin explicitly supports them. Just floating ideas.

**Comment by toolmantim** [comment]
I think it makes sense to add a `userns_mode` option, I just wanted to check that it'd work in an elastic stack setup.

Just for context/understanding, why not change it in your docker-compose configuration file?

**Comment by s01ipsist** [comment]
@toolmantim - great question.  🤦‍♂️ I completely lost sight of how the plugin functions to call, and optionally overwrite, the docker-compose config. The `--extra-args` concept is nonsense with that exposed, as is any real need to expose this `userns_mode` configuration. Perhaps the readme could restate similar at the end of the arguments listing, perhaps I just missed the wood for the trees.

**Comment by toolmantim** [comment]
😁 No worries!
