### ISSUE TITLE
Error Exit Status 1: "docker inspect" requires at least 1 argument.

### ISSUE THREAD

**Issue by williams4027** [buildkite-plugins/docker-compose-buildkite-plugin#220]
This morning we ran into some errors on our CI builds after the commands run successfully:

`"docker inspect" requires at least 1 argument.`

Looking through the code, it seems that this is due to the new check that was added in `run.sh`. I have included a build log, but wasn't sure what was incorrect with our setup. We are also using the Buildkite cloud formation stack. This also only affected one of our pipelines, but we rolled back the versions on all the others to be safe. Any thoughts?

Solution:
For now we rolled back to v3.0.2.

[root-mobile-server-integration_build_21518_generating-coverage-report.log](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/files/3135216/root-mobile-server-integration_build_21518_generating-coverage-report.log)

**Comment by dgarbus** [comment]
We are also seeing this today for the first time, but are using an older version of the compose plugin (2.6.0).

**Comment by pecigonzalo** [comment]
@williams4027 This should be fixed now, could you verify?

**Comment by williams4027** [comment]
Sorry for the delay, I just ran the build using `40424b7` on one of our CI pipelines and was successful. That looks to have fixed it. Thanks everyone for the quick response!
