### ISSUE TITLE
Retry on Docker failure

### ISSUE THREAD

**Issue by nijave** [buildkite-plugins/docker-compose-buildkite-plugin#227]
Occasionally the Docker daemon will fail (usually due to heavy load). Is there any way to set a retry on this? It looks like the only options are on image operations

**Comment by toolmantim** [comment]
Sounds like the `pull-retries` and `push-retries` options might be what you need @nijave?

**Comment by nijave** [comment]
These aren't pulls or pushes, they're the actual build (docker-compose
build) so I don't think those will have any effect

**Comment by toote** [comment]
Adding the logic to be able to do that may be quite cumbersome for little gain. Flaky tests are the bane of every engineer so I completely understand how frustrating they can be. Unfortunately, I believe they are a symptom of an issue and retries are not a solution just a bandaid.

That said, buildkite does offer some alternatives: you can retry the step itself off buildkite's UI or using [steps' retry attributes](https://buildkite.com/docs/pipelines/command-step#retry-attributes) for it to be done automatically.
