### ISSUE TITLE
Support propagate-environment

### ISSUE THREAD

**Issue by pecigonzalo** [buildkite-plugins/docker-compose-buildkite-plugin#230]
It would be great to support `propagate-environment` as done in https://github.com/buildkite-plugins/docker-buildkite-plugin

**Comment by ianwremmel** [comment]
Was about to open a request for this. I'm currently doing this janky bash/awk thing, but it can only pass through the variables that are set on the box doing pipeline upload, it can't automatically know about env keys (I had to add NODE_ENV manually): 

```bash
docker_compose_environment: &docker_compose_environment
  - AWS_DEFAULT_REGION
$(env | awk -F= '/^BUILDKITE/ {print "  - " $1}')
  - CI
  - NODE_ENV
EOT
```
