### ISSUE TITLE
buildkite sometimes using old image from depends_on

### ISSUE THREAD

**Issue by mashbourne** [buildkite-plugins/docker-compose-buildkite-plugin#234]
I have a docker compose file defining a test image with entry point that runs the tests called `test`. It has a `depends_on` section with my `test-db` which is a service pointing at an image in artifactory with a `latest` tag.

It seems like the plugin is using older version of the image despite newer version published with same tag name.

On local machine, doing `docker-compose down; docker-compose pull test-db; docker-compose run test` always ends up pulling the newest dependency image.

**Comment by neville1355** [comment]
+1, we have an image with two depends_on and when booting up the depended containers start with a `_1` name instead of a `_<build_number>` name

**Comment by neville1355** [comment]
It turns out we were experiencing this because we were not `pull`'ing our dependencies within our pipeline.yml.

Configuring our build step to push to a repo, and then explicitly pulling it helped resolve it for us.
