### ISSUE TITLE
Push along with build step

### ISSUE THREAD

**Issue by ngan** [buildkite-plugins/docker-compose-buildkite-plugin#237]
My usage of this plugin is as follows:

step 1. Pre-build image using `build` and `cache-from`:
```
          cache-from:
            - foo:1234.dkr.ecr.us-west-2.amazonaws.com/foo-build:foo-${BUILDKITE_BRANCH}
            - foo:1234.dkr.ecr.us-west-2.amazonaws.com/foo-build:foo-master
```
step 2. wait
step 3. Push the pre-built image using `push`:
```
          push:  foo:1234.dkr.ecr.us-west-2.amazonaws.com/foo-build:foo-${BUILDKITE_BRANCH}
```

It feels a little redundant to bring up a whole step just to push the image that was built in step 1. Is it possible to push the same image to multiple tags in step 1?

**Comment by ngan** [comment]
I just saw this: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/224 -- any plans on getting that in here?

**Comment by taylorzr** [comment]
Seems like it's in 3.1 just no docs on it: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/releases/tag/v3.1.0

**Comment by ngan** [comment]
Ah yes, I've been using it. Forgot I had this issue open.
