### ISSUE TITLE
Error with #210

### ISSUE THREAD

**Issue by timle-root** [buildkite-plugins/docker-compose-buildkite-plugin#241]
I had some pipelines that didn't specify the docker-compose plugin version (they do now). They started failing this morning and it appears related to #210. The error in the buildkite log is 

`[2019-11-01T12:11:56Z] /var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-docker-compose-buildkite-plugin/hooks/../lib/run.bash: line 23: containers[@]: unbound variable`

Our bad for using `master` and I've since fixed that - just wanted to let you know. Thanks!

**Comment by jufemaiz** [comment]
I can confirm I'm seeing this one all my docker-compose pipelines.

**Comment by lox** [comment]
Sorry folks, we'll get a fix out shortly!
