### ISSUE TITLE
Support scaling services

### ISSUE THREAD

**Issue by jorge-wonolo** [buildkite-plugins/docker-compose-buildkite-plugin#264]
I am looking into ways to speed up some tests and I would like to use docker-compose scale feature to increate service instances dynamically depending on the scope of the task I will be performing.   

Is support for scale in the plugin feasible?

**Comment by evandam** [comment]
Any updates on this? Seems like it would be helpful to be able to pass a `docker-compose up --scale=x ...` for dependencies.

Thanks!

**Comment by lox** [comment]
It would be a pretty straightforward thing to add, interested to hear a bit more about the use-case!

**Comment by jorge-wonolo** [comment]
@lox thanks for looking into it.  My use case is to run selenium tests on a grid with N browsers.  The number of browsers should match the number of process the tests harness is running in parallel.  Having a scale option will allow me to arbitrarily set the number of browsers and test process dynamically.

**Comment by toote** [comment]
It may be an interesting idea to implement. But it would appear that this is supported directly in the docker compose file by using the [`scale` property](https://docs.docker.com/compose/compose-file/#scale) of a service element. Granted, that has been deprecated in favor of the replicated deployment with the [`replicas` configuration](https://docs.docker.com/compose/compose-file/deploy/#replicas).

Or do you still think that a plugin-specific option is still warranted?
