### ISSUE TITLE
Running dependency step 

### ISSUE THREAD

**Issue by chetushivanna** [buildkite-plugins/docker-compose-buildkite-plugin#270]
Hi,
I am noticing an issue when we are starting  the dependency.  since you are using docker-compose up {service name} if there is any previous existing image is present in the buildkite agent then it uses that image instead of build the new image . so that we cant test our code for the changes.
https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/commands/run.sh#L177-L179

can we change that line to add the parameter --build 

Thanks

**Comment by toote** [comment]
Hi @chetushivanna! So sorry for the looong delay in getting back to you (but I believe  I checked that everything I'm mentioning here was actually true when you opened this issue).

As far as I understand, to guarantee the behaviour you mention you have the `pull` option of the plugin where you can list all the images that [will be pulled](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/9030a1201114292f76319f7ac329df1cd220bf01/commands/run.sh#L41-L53) before bringing up the dependencies and then running the service. What's more, it will try to get the specific ones built in a previous `build` step that uses this same plugin (that is what the `get_prebuilt_image` in line 43 does).

Or did I misunderstand your issue?
