### ISSUE TITLE
Buildx support for arm containers

### ISSUE THREAD

**Issue by nitrocode** [buildkite-plugins/docker-compose-buildkite-plugin#291]
For now, I'm using `make` commands to setup the builder and run the `docker buildx build` commands. I'd like to use this plugin to build my containers with arm support.

Since there wasn't a ticket with `buildx`, I thought I'd create this for now.

**Comment by toote** [comment]
Could you elaborate on how you use `buildx` commands with docker compose?

I am not too familiar with the command and its capabilities, but it does not seem to be related so I don't think that the functionality it provides should live in this plugin. Or am I missing something?
