### ISSUE TITLE
Option to skip pulling images?

### ISSUE THREAD

**Issue by evandam** [buildkite-plugins/docker-compose-buildkite-plugin#292]
Hi folks,

In light of DockerHub's rate limiting, is it possible to skip attempting to pull images every time before running a step? (https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/commands/run.sh#L73)

As far as I know, docker-compose will pull the image down if it needs to, or otherwise just use the local image.

It would be great to have something like `force_pull: false`.

**Comment by kymikoloco** [comment]
For our use case, I build the image my service needs in a previous step and it is local only (as it is 60gb and easier to build and keep on the machine), the plugin fails trying to `--pull` an image that will never be on a remote.
