### ISSUE TITLE
Bad substitution when using `cache-from` when `.` is used

### ISSUE THREAD

**Issue by ianks** [buildkite-plugins/docker-compose-buildkite-plugin#293]
Similar to #151:

```
/var/buildkite/plugins/github-com-buildkite-plugins-docker-compose-buildkite-plugin-v3-7-0/hooks/../commands/build.sh: line 29: cache_from__us.gcr.io/adhawk_share/tatami: bad substitution
```

**Comment by toote** [comment]
Took me a while to understand the error without the actual pipeline configuration but I believe that the issue is not `-` but `.` in the cache-from options that need to be removed/translated

**Comment by toote** [comment]
I have created PR #343 to fix the handling of periods in service names.

That said, after looking at the code base a lot more and being more familiar with it, the actual issue @ianks had was the lack of the service name in the `cache-from` stanza. The way that option works it assumes that it will be of the form `SERVICE:URL:TAG:GROUP` (where `GROUP` is optional and only added recently). The service name is important and is used to process when there are several image alternatives or preferences and can not be omitted. When you do so, it is assumed the `URL` is the service name and URLs can have characters that are not valid service names so all the assumptions on it go out the window and end up in the error shown in the following line: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/4d20d265c9b6cffbebf8700c61b1784783319e6c/commands/build.sh#L52
