### ISSUE TITLE
Docker Compose Project isolation within a single buildkite job ID

### ISSUE THREAD

**Issue by woodhull** [buildkite-plugins/docker-compose-buildkite-plugin#294]
Hello!

We're running a Docker Compose Plugin powered build for a large rails app. The build is split up via knapsack across dozens of machines. 

Everything works great when there is one buildkite agent running on each machine. However each machine has multiple CPUs so we would like to get more parallelism by running multiple buildkite agents. When there is more than one agent on each machine the knapsack build steps fail, while other build steps that are unique per job ID succeed. 

Looking at the code it looks like `docker_compose_project_name` is based on the buildkite job ID which seems right.

https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/07607ad023752fc409b0a2dd5af7feafb265271a/lib/shared.bash#L83

I see that is assigned to the container name, but do not see anything that sets the `--project` flag. Not sure if that is a problem or not. 

We're continuing along with one agent per machine for now, but eager to ramp paralellism up to save costs if there are any tips I'm missing.

**Comment by toote** [comment]
Hi @woodhull! sorry for the long delay in responding. 

I reviewed and even back when you reported the issue the `run_docker_compose` function that was used everywhere to run stuff added the `-p` option:

https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/07607ad023752fc409b0a2dd5af7feafb265271a/lib/shared.bash#L186

If your builds were failing there was obviously something else going on, but we would need more information to further troubleshoot it. Is this still a concern of yours?
