### ISSUE TITLE
Propagate Buildkite Artifact env vars with mount-buildkite-agent

### ISSUE THREAD

**Issue by evandam** [buildkite-plugins/docker-compose-buildkite-plugin#302]
When mounting the `buildkite-agent`, can the following env vars also be propagated so uploading artifacts works as expected?

```
BUILDKITE_ARTIFACT_UPLOAD_DESTINATION
BUILDKITE_S3_DEFAULT_REGION
BUILDKITE_S3_ACL
```

Not sure what else might be needed for artifact destinations besides S3.

**Comment by toote** [comment]
For reference, the complete list of environment variables needed for artifact uploading to your private S3 buckets are documented in the [`artifact` agent command](https://buildkite.com/docs/agent/v3/cli-artifact#using-your-private-aws-s3-bucket).

It may be interesting to see if implementing #61 would be enough to support this use-case or there will need to be special handling for these variables.

That said, supporting this use case would also require supporting the other two customized destinations for artifacts: [Artifactory](https://buildkite.com/docs/integrations/artifactory) and [GCloud](https://buildkite.com/docs/agent/v3/cli-artifact#using-your-private-google-cloud-bucket).

**Comment by toote** [comment]
Created PR #344 to implement the `propagate-environment` option that is very likely to take care of this
