### ISSUE TITLE
Not cleaning up on cancel

### ISSUE THREAD

**Issue by piotrb** [buildkite-plugins/docker-compose-buildkite-plugin#31]
It seems like when a job is cancelled, either via manual cancel or though timeout, dependant services (like db, redis, etc), and sometimes the main test process if its stuck, get just left behind on the test hosts (this understandably severely impacts memory availability and such)

**Comment by lox** [comment]
I believe this is tied to https://github.com/buildkite/agent/issues/389. Once that is fixed, this will stop happening.

**Comment by toolmantim** [comment]
This should be fixed on the most recent stack thanks to the new beta agent having this fixed too.
