### ISSUE TITLE
Unnecessary intermediary steps when pushing a pre-built image?

### ISSUE THREAD

**Issue by rafaelmagu** [buildkite-plugins/docker-compose-buildkite-plugin#314]
It may be related to the behaviour seen in #313, but I figured that issue covers a different use case.

I'm asking the plugin to push a pre-built image using a specific tag, and it does that, but it first tags the image using the `:master` tag (which I've determined to come from the "service image" resolution code in the plugin's helpers). 

It appears to do the following for a given tag (`:build-1234`):
1. Pull pre-built image (uses commit sha as tag)
2. Tag pre-built image as `:master`
3. Re-tag `:master` as the tag I want (`:build-1234` in this case)
4. Push `:build-1234` up to repo

Why does it need the intermediary step?

**Comment by toote** [comment]
@rafaelmagu sorry for the delay in getting back to you.

I looked at the repository's history to try to find the reasoning for that. After reading a lot of PRs and discussions and not finding anything I slowly ran through the tests until I figured it out.

First, the prebuilt-images are tagged as necessary for them to be correctly mapped to the images of each service in the docker compose file (see the [`compose_image_for_service` function](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/lib/push.bash#L3)). If there is no image specification it is just called as the service itself (which I assume is the `master` tag you mention). Finally, if you just specified a service name as the `push` configuration, then the image property of your docker compose file should be respected, for which it needs to exist (explaining the previous step). But if you used more remapping in your configuration the new tag is created (`build-1234` in your example I assume) and pushed.

Could it be optimized? Almost as sure that it could as I am that a lot of use-cases will break when we try to do so :P

If that was not it, do you have the configuration example of the plugin for us to take a look at exactly what is happening here? In the meantime, I'm closing this issue

**Comment by rafaelmagu** [comment]
Thanks, that appears to map to what I found. The concern is that it is _pushing_ the `master` tag alongside the `build-1234` one. But as you described, it looks like the issue is in my config. I'll investigate further.
