### ISSUE TITLE
pre-command and post-command runs in docker container

### ISSUE THREAD

**Issue by kbaum** [buildkite-plugins/docker-compose-buildkite-plugin#32]
Currently if I create a pre-command or post-command it runs outside of my docker container.  Given that my test environment sits within docker, i would rather by default the hooks was run within the context of the same docker container my tests will run in.  This will give me the chance to run setup tasks like installing assets and post command like caching assets for the next build.

thx.

**Comment by lox** [comment]
Sorry for the radio silence on this one, been pondering how this fits into future plans for the agent and for the docker-compose plugin.

I think that as it stands, the pre-command and post-command hooks need to be in the domain of the agent. Will talk over with the team where your suggestion might make sense.

**Comment by kbaum** [comment]
I wrote this a while back and I think what you are saying makes sense.  Will close this one. Thanks!

**Comment by jkugler** [comment]
We have come up with a need for this. The post-command hook needs some resources inside the docker container to run, and we don't want to install all these resources on the agent. Has anyone come up with a way to do this?
