### ISSUE TITLE
Support for versionless compose files

### ISSUE THREAD

**Issue by cphalpin** [buildkite-plugins/docker-compose-buildkite-plugin#320]
Compose files under the [compose specification](https://github.com/compose-spec/compose-spec/blob/master/spec.md#compose-file) no longer contain a version.

When I try to build images from a versionless compose file I get an error like "The 'build' option can only be used with Compose file versions 2.0 and above."

**Comment by toote** [comment]
Sounds exactly what is being worked on in #307
