### ISSUE TITLE
Allow interpolation for `volumes`

### ISSUE THREAD

**Issue by ngan** [buildkite-plugins/docker-compose-buildkite-plugin#324]
I'm using the plugin like such:
```
  - docker-compose#v3.9.0:
      run: coolapp
      ansi: false
      volumes:
      - "$$PATH_TO_MY_BINARY:/usr/bin/foobar"
```

But when this executes, the `$PATH_TO_MY_BINARY` is not interpolated in bash. It used as a raw argument in the `docker-compose` command:

```
$ docker-compose -f .buildkite/docker-compose.yml -p buildkite40d06312fc41497a96f8fa4f5e0d70e8 --no-ansi run --name buildkite40d06312ac41497a96f8fa4f5e0d70e8_coolapp_build_513190 -v $PATH_TO_MY_BINARY:/usr/bin/cache --rm coolapp /bin/sh -e -c 'dosomething'

Cannot create container for service coolapp: create $PATH_TO_MY_BINARY: "$PATH_TO_MY_BINARY" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path
```

I can't seem to tell where along the way does the interpolation fail to happen?
https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/commands/run.sh#L94-L96
https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/lib/shared.bash#L37-L39
https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/master/lib/shared.bash#L42-L57

**Comment by toote** [comment]
This appears to be the same issue as https://github.com/buildkite-plugins/docker-buildkite-plugin/issues/189... will review what can be done about it
