### ISSUE TITLE
Some tools to smartly wait for compose services

### ISSUE THREAD

**Issue by piotrb** [buildkite-plugins/docker-compose-buildkite-plugin#33]
This is a feature request .. just to be clear, not expecting this behavior, but would be nice since it seems like its needed by everyone just about ..

I had to write a bunch of code to ensure that linked services such as mysql were actually up before running code, it might make sense to automate this somehow.

I've been using https://github.com/betalo-sweden/await as a quick helper for this it seems to be a fairly small protocol aware waiter

**Comment by lox** [comment]
This is consistently a pain for me as well, but I don't think that solving it in this plugin is the right spot. 

A lot of work is happening in the docker space around healthchecks and docker-compose has recently supported these in depends_on checks: https://github.com/docker/compose/pull/4163. 

I'll leave this open in case you have any follow up questions or suggestions on how we could make this easier.

**Comment by toolmantim** [comment]
Yeah, this is a pain too. But I don't see this ever being in scope for this plugin, because it's something being addressed in Docker/Compose. I'm going to close this for now.
