### ISSUE TITLE
add mount-checkout option from docker-buildkite-plugin

### ISSUE THREAD

**Issue by TSMMark** [buildkite-plugins/docker-compose-buildkite-plugin#331]
Hi, would it be possible to add the `mount-checkout` or `copy-checkout` option from `docker-buildkite-plugin` implemented here:

https://github.com/buildkite-plugins/docker-buildkite-plugin/pull/182

Or maybe this is already possible to do and undocumented? I think this would save a ton of time on certain builds

**Comment by TSMMark** [comment]
Basically I want to cp files from the host into the container, and I want to avoid docker volumes.

Any way to use docker compose cp command directly using `docker-compose-buildkite-plugin`? https://docs.docker.com/engine/reference/commandline/compose_cp/

**Comment by toote** [comment]
This is now part of the latest release v4.4.0 :)
