### ISSUE TITLE
Shell script structure prevents graceful handling of timeouts

### ISSUE THREAD

**Issue by huguesb** [buildkite-plugins/docker-compose-buildkite-plugin#333]
When a buildkite job exceeds its timeout specification, the buildkite agent will first send a TERM signal, and then, after a configurable time period, forcefully kill the job with a KILL signal. This is fairly standard practice.

Unfortunately, this plugin wraps the call to docker-compose in a bash script, and bash is notoriously awful at signal propagation. This means that even if the underlying application is attempting to catch the TERM signal and gracefully terminate on timeout, it will *never* receives the TERM signal, and instead *always* be forcefully killed.

To solve this problem, the shell script must go through a complicated dance of enabling job control, setting handlers, invoking long-running commands in the background and then waiting on them, ...

Alternatively, the simplest way to avoid the quagmire of signal handling in bash, is to only have one long-running command, make sure it's the last one in the script, and `exec` into it. This approach would, at minimum, require:
1. moving the check for failed containers out of the `command` hook, into a `post-command` or `pre-artifact` hook
2. disabling the combined run & push mode (is that really a thing people use?)

**Comment by toote** [comment]
@huguesb that is indeed quite an interesting point... unfortunately it is a lot more complicated than that. In particular, you also have the docker runtime environment (that can setup or change signals for each container image) and the processes running inside each of them. Let alone the fact that we need to make sure that cancelled jobs do run cleanup steps, only guaranteed to happen in the `pre-exit` hook.

While I don't have hard data, I assume that the combined run and push mode may be something that people use or it wouldn't be there.

But a good proposal may be a good enough argument to make the switch. Would you care to start working on a PR to make the change on the existing codebase?
