### ISSUE TITLE
cache-from option requires tag

### ISSUE THREAD

**Issue by dancallaghan** [buildkite-plugins/docker-compose-buildkite-plugin#349]
With the changes in v4.1.1, the plugin is now erroring if a tag is not defined in the `cache-from` configuration option.

I believe before this change it had the same functionality as `docker pull`, where if a tag was not specified it would fallback on latest.

**Comment by toote** [comment]
This was done for validation purposes as well as grouping cache-froms and we didn't consider that scenario (I personally prefer being explicit but wouldn't want everyone that uses it that way to have to update all their pipelines).

Thanks for letting us know! I created PR #350 to correct this :)

**Comment by dancallaghan** [comment]
Great, thanks for the speedy response! I'm in favour of being explicit as well, but it's a bit of a heavy-handed change for a patch release :)
