### ISSUE TITLE
Plugin fails to acquire lock, then is unable to open it

### ISSUE THREAD

**Issue by BRMatt** [buildkite-plugins/docker-compose-buildkite-plugin#35]
![](https://cl.ly/3e3D1J1U1z2t/Image%202017-03-07%20at%2011.22.54%20am.png)

Here's the raw log:

```
~~~ Setting up plugins
[90m# Could not aquire lock on "/var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-docker-compose-buildkite-plugin.lock" (Locked by other process)[0m
[90m# Trying again in 1 second...[0m
[90m# Could not aquire lock on "/var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-docker-compose-buildkite-plugin.lock" (Locked by other process)[0m
[90m# Trying again in 1 second...[0m
[31m🚨 Buildkite Error: open /var/lib/buildkite-agent/plugins/github-com-buildkite-plugins-docker-compose-buildkite-plugin.lock: no such file or directory[0m
^^^ +++
```

And here are the details of the agent:

```
aws:ami-id=ami-f9d809ef aws:instance-id=i-08e499a4ba6771846 aws:instance-type=c4.xlarge buildkite-aws-stack=v2.0.0-rc5-2-g2f723b2 docker=1.13.1 queue=default stack=buildkite-ci-agents
```

I believe a bunch of jobs started on this node at the same time. I also noticed that one of the other jobs on the same node failed with this error:

![](https://cl.ly/20180l0P2c36/Image%202017-03-07%20at%2011.27.35%20am.png)

**Comment by toolmantim** [comment]
This looks like a bug with https://github.com/buildkite/agent. Do you know what agent version this was? Beta 17 included a fix for this problem I believe https://github.com/buildkite/agent/releases/tag/v3.0-beta.17

**Comment by toolmantim** [comment]
I'm going to close this, because I think it's related to that above bug. Bug if it's a problem with the plugin, feel free to re-open it! Thanks!
