### ISSUE TITLE
Push without prebuilt image fails when using docker-compose v2

### ISSUE THREAD

**Issue by tomgi** [buildkite-plugins/docker-compose-buildkite-plugin#352]
We've recently upgraded to Docker Compose v2 and configured docker-compose-buildkite-plugin to use the new cli (`cli-version: 2`)

We've noticed that some of our `push` steps have started failing when they have no prebuilt image available (i.e. when a pipeline doesn't have a separate `build` step before the `push` step). 

Here's a truncated error log:
```bash
:docker: Building app
...
#16 exporting to image
#16 exporting layers done
#16 writing image sha256:XXX done
#16 naming to docker.io/library/XXX-app 0.0s done
#16 DONE 0.0s
...
:docker: Pushing image XXX/YYY:release-123
$ docker tag XXX_app XXX/YYY:release-123
Error response from daemon: No such image: XXX_app:latest
```

Notice the difference in the image name - `XXX-app` vs `XXX_app`.

This seems to be caused by a change in the image naming convention between Docker Compose v1 (Python) and v2 (Go).

```python
def rename_to_tmp_name(self):
        """Rename the container to a hopefully unique temporary container name
        by prepending the short id.
        """
        if not self.name.startswith(self.short_id):
            self.client.rename(
                self.id, '{}_{}'.format(self.short_id, self.name)
            )
```

https://github.com/docker/compose/blob/5db8d86f127848367e4d721e992c188923c89d42/compose/container.py#L260

```go
// Separator is used for naming components
var Separator = "-"
```

https://github.com/docker/compose/blob/0062703bea796eca5b5f78a4779fa166cc18619c/pkg/compose/compose.go#L36

**Comment by toote** [comment]
Great find and thanks a lot for the PR!

I have merged it and will be released in the next version (most likely next week)
