### ISSUE TITLE
imprecise start time in log

### ISSUE THREAD

**Issue by xxchan** [buildkite-plugins/docker-compose-buildkite-plugin#373]
I feel this step takes a while but it's time is 1s or 0s. It seems it's time is included to the next log. I added the log `Begin xxx.sh` at the beginning of my script and it looks so.

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/37948597/218449972-8cd08f9d-b113-45c3-bbcc-1bf6e5c9a0bd.png">

**Comment by toote** [comment]
This was indeed a head-scratcher!

After a lot of testing and digging around I finally got to the end of it: it is a bug in the agent and ansi-timestamps with groups that are too short (1 or 2 lines only). Which appears to be the case for the Running commands most of the time as you normally run scripts that start off their output with a group :(

I have created a minimal pipeline that doesn't use any fancy feature or plugin whatsoever and [reported the issue in the agent itself](https://github.com/buildkite/agent/issues/1957) so I will be closing this issue as it is not particular to this plugin :)
