### ISSUE TITLE
SSH passed as boolean instead of string to docker-compose

### ISSUE THREAD

**Issue by jklafka-rokt** [buildkite-plugins/docker-compose-buildkite-plugin#382]
In #347, the plugin added support for passing `--ssh` to the `docker-compose` build command in BuildKite as a boolean option. However, docker-compose takes `--ssh` as a string ([doc](https://github.com/docker/compose/blob/6a374284919b5e791bcef1e2b56d7ecb30184648/docs/reference/compose_build.md?plain=1#L16) and [code](https://github.com/docker/compose/blob/6a374284919b5e791bcef1e2b56d7ecb30184648/cmd/compose/build.go#L46)). 

You can see this when running `docker-compose` locally. For example, this fails:

```bash
$ docker-compose build <project> --ssh

flag needs an argument: --ssh
```

Passing in `default` for default SSH works:

```bash
$ docker-compose build <project> --ssh default

[+] Building 5.6s (21/21) FINISHED
...
```

**Comment by toote** [comment]
Great catch! I have created PR 383 to fix the issue :)
