### ISSUE TITLE
Collapsed log output for builds

### ISSUE THREAD

**Issue by chendo** [buildkite-plugins/docker-compose-buildkite-plugin#402]
I've implemented collapsed log output for Buildkit-enabled builds in my fork: https://github.com/chendo/docker-compose-buildkite-plugin/commit/0806a871e5d6c3268a4a21b20684968ddb06f471

This makes it easier to understand which part of the build is taking up time. It would be great to have this in the official plugin IMO.

<img width="1093" alt="image" src="https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/assets/2661/936a2a27-adc0-413f-869c-c012a2426c65">

**Comment by deanpcmad** [comment]
This looks great. Does it also prevent the truncation warning?

**Comment by pzeballos** [comment]
Interesting @chendo! we should probably test more scenarios before adding it to the plugin, and maybe as an option 🤔. Do you know how this would work if you disable buildkit?

**Comment by toote** [comment]
FYI: this enhancement has been incorporated as part of the major overhaul being done for the next major release (see #417)
