### ISSUE TITLE
pre-run-dependencies is broken with Docker Compose >=2.23.1,<2.24.0

### ISSUE THREAD

**Issue by erickpeirson** [buildkite-plugins/docker-compose-buildkite-plugin#413]
There appears to be an unfortunate interaction between https://github.com/docker/compose/issues/11237 in Docker Compose and the `pre-run-dependencies` behavior in this plugin. Since this plugin runs Compose with `up --wait -d --scale {run_container}=0 {run_container}`, this trips the bug linked above, causing errors like this on startup:

```
buildkite018c645270ad4334be7e897b875f9049 is missing dependency {run_container}
```

Disabling `pre-run-dependencies` is a workaround until the BuildKite AMI is updated with a newer Docker version.

**Comment by pzeballos** [comment]
Hey @erickpeirson! thanks for bringing this to our attention. I'm guessing you are using an Elastic Stack v6.11 or higher, right? Can you raise this in the [Elastic Stack](https://github.com/buildkite/elastic-ci-stack-for-aws) so the team can bump the docker-compose to 2.24?
