### ISSUE TITLE
Malformed image uri generated in try_image_restore_from_docker_repository()

### ISSUE THREAD

**Issue by sjauld** [buildkite-plugins/docker-compose-buildkite-plugin#45]
The latest update seems to cause the docker pull command to look like this:

`docker pull $'\E[90m$\E[0m buildkite-agent meta-data get docker-compose-plugin-built-image-tag-web\n123456789012.dkr.ecr.ap-southeast-2.amazonaws.com/my-ecr-repo:my-image'`

This seems to be the cause: https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/fd513c17b75649f56197e236add798e135267eb4/hooks/commands/run.sh#L41

plugin_get_build_image_metadata uses plugin_prompt_and_must_run which returns \033[90m$\033[0m along with the actual command

**Comment by lox** [comment]
Apologies, I'll investigate this and get a fix out shortly.

In the meantime, I'd strongly suggest tagging your docker-compose plugin usage to a stable version:

```
steps:
  - command: test.sh
    plugins:
      docker-compose#v1.1:
        run: app
```

**Comment by sjauld** [comment]
Excellent advice!

**Comment by lox** [comment]
Naturally the one thing that I couldn't write tests for broke :)

**Comment by lox** [comment]
This should be fixed. If you get a chance to try it, could you leave a comment and I will re-open? Apologies for the inconvenience and thanks for the report!

**Comment by sjauld** [comment]
Just reran the broken build on master branch and it's all good now. Cheers!
