### ISSUE TITLE
Add support for configuring retries for pull/push operations

### ISSUE THREAD

**Issue by KevinGrandon** [buildkite-plugins/docker-compose-buildkite-plugin#57]
We're currently seeing some flakiness with docker images when both uploading and downloading. It would be great if there was a configuration option to enable exponential backoff retrying.

I'm not sure if you have granular control over a single option, or if all of the docker steps would have to be retried. E.g., I'm pulling a lot of images during a build step and one fails. Would it be possible to retry just that package, or would we need to pull all images again?

**Comment by lox** [comment]
Getting started in https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/58.

**Comment by lox** [comment]
Done!
