### ISSUE TITLE
Support --user (custom value or buildkite-agent)

### ISSUE THREAD

**Issue by bendrucker** [buildkite-plugins/docker-compose-buildkite-plugin#64]
Hey there!

I've been wrestling with the best way to handle mounted volumes from the host. When Docker runs as root (id=0), the files it writes to the mounted volume are owned by root. Buildkite fails with a permissions error on any remaining files when it goes to `git clean` the repo on the next job.

On `buildkite-agent@2`, I was getting around this with a `pre-command` hook that ran `export UID` and then a `user: $UID` property in my `docker-compose.yml` file. I noticed that with the plugin, this variable is not exposed to the plugin script and compose treats it as missing.

I'd love to be able to either specify a user through the plugin or ideally instruct the plugin to pass the user ID who executed it.

I haven't thought about an API for this, just wanted to get my thoughts down and see if you'd considered this.

Thanks!

**Comment by lox** [comment]
Would something like https://github.com/buildkite-plugins/docker-buildkite-plugin/pull/2 provide a short-term solution?

**Comment by bendrucker** [comment]
I don't think passing `UID` at runtime addresses this, if that's what you're thinking. This is specifically the `docker(-compose) run --user` option or `services.*.user` in the YAML file.

**Comment by lox** [comment]
Ah right, apologies, I was assuming you were passing in `UID` and `GID` as env and then using chown internally. Sorry! 😰

We can easily support `--user`. 

Out of interest, have you tried the `userns` stuff as an alternative? https://docs.docker.com/engine/security/userns-remap/

**Comment by bendrucker** [comment]
I did check out `userns` when I was exploring this stuff today! I instinctively ignored it since it's at the daemon level. Might work in my setup, not too many other things use Docker on those instances at the moment, but it could cause other problems I guess. 

For now I just exposed env vars and the agent binary into the container since that'll work anywhere. Figured it was better to be explicit than go changing global Docker settings.

**Comment by Soliah** [comment]
Is there a work around for this in the meantime?

**Comment by Soliah** [comment]
Work around for us using the buildkite-agent v3 is to use a `pre-command` hook and set an env var to the UID of the user running the agent with `id -u`. Then specifying this inside our `docker-compose.yml`

**Comment by bendrucker** [comment]
I don't need this anymore so I'm gonna close it out
