### ISSUE TITLE
Change output to closed unless failed

### ISSUE THREAD

**Issue by Vektah** [buildkite-plugins/docker-compose-buildkite-plugin#65]
Using +++ [here](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/7a84e183ef16722671dc7a2889f2bb983ce25356/hooks/commands/run.sh#L35
)  means builds will have the docker build logs expanded by default. This is usually undesirable as you need to scroll through pages of output before you can see your tests.

Wasn't there some magic for "collapse unless failed", maybe `~~~`?

**Comment by lox** [comment]
Yup, agreed. It gets conditionally expanded if it fails anyway at https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/7a84e183ef16722671dc7a2889f2bb983ce25356/hooks/commands/run.sh#L52
