### ISSUE TITLE
docker-compose version parsing is very naïve

### ISSUE THREAD

**Issue by ticky** [buildkite-plugins/docker-compose-buildkite-plugin#67]
The code that parses the docker-compose file version https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/blob/7a84e183ef16722671dc7a2889f2bb983ce25356/lib/shared.bash#L78-L81 will break if, for instance, the user adds an extra space before the version string. It’ll also fail if the version is not specified as a string, and has no protections against matching a string specified in any key ending in `version`.

It also lacks any sort of fallback or error message if it fails to find a version number.

**Comment by toolmantim** [comment]
#68 fixes these, and I've added a Readme item on how to run the tests too.
