### ISSUE TITLE
Images should be deleted after building

### ISSUE THREAD

**Issue by Soliah** [buildkite-plugins/docker-compose-buildkite-plugin#77]
Since the build always pushes up to a registry and there isn't a way to execute a command after the build I think images should be cleaned up after building since steps are inherently stateless.

**Comment by lox** [comment]
We rely on the images being there for subsequent steps. I'd suggest using a different ECR repository specifically for buildkite CI images and then use the new https://docs.aws.amazon.com/AmazonECR/latest/userguide/LifecyclePolicies.html. If you aren't on ECR, then it's slightly more complicated.

**Comment by Soliah** [comment]
@lox I was told by @toolmantim in Slack that steps should be stateless as the agent it runs on could be different from the build step. Is this not the case?

**Comment by toolmantim** [comment]
There might be some confusion! Are you referring to local images @soliah? You’re probably right that they’re fine to untag/remove after building… just have to figure out what to do about the layer cache tho? Because dedicated builder agents often need that around for performance.

**Comment by lox** [comment]
Oh, apologies I misunderstood! Yup, I'd suggest leaving them around to ensure a hot build cache.

**Comment by Soliah** [comment]
Yea sorry I meant local images. I guess as the number of agents increases the cache becomes less useful as the chance of hitting the same agent when you have a lot of pipelines goes down.

In any case I don't think this is something that should be dealt with in the plugin.

**Comment by toolmantim** [comment]
Oh right, yeah sometimes the build step is often targeted to a single pool of "builder" agents, but I totally agree it gets less useful for caching. It'd be great to extend the build cache support to include pulling images and using `--cache-from` — but in the meantime, I think people rely on the builds hitting mostly cached/hot agents.

Thanks for filing an issue though! This discussion is good for future peeps wondering the same thing.

**Comment by lox** [comment]
Are you seeing any problems with images building up, or are you just concerned that it might become a problem @Soliah? We've tackled this a few different ways in the past.
