### ISSUE TITLE
Ability to pull multiple images in run step

### ISSUE THREAD

**Issue by ritchiey** [buildkite-plugins/docker-compose-buildkite-plugin#86]
Hi,

I'm attempting to run tests of our whole suite (our clients and servers are in separate repos).

To do this, I've created a parent repo with the other repos as submodules. I've created a pipeline and docker-compose files in the parent repo so that Buildkite can build and run the child project images.

I would like to pre-build the images but find that when it hits the run step, it only pulls the image that I'm running, and then proceeds to rebuild the other images specified in docker-compose.yml.

I had a quick look through the plugin code and found this comment:

> We only look for a prebuilt image for the service being run. This means that
> any other services that are dependencies that need to be built will be built
> on-demand in this step, even if they were prebuilt in an earlier step.

Is this something that's likely to change?

Thanks
Ritchie

**Comment by lox** [comment]
It's certainly possible that it could be made to work. The issue is that it would require pretty extensive parsing of the docker-compose file to figure out dependencies.

Perhaps we could have a way of specifying additional pre-built images to pull before run?

**Comment by lox** [comment]
Some notes on how I've personally worked around this issue before in https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/issues/47

**Comment by ritchiey** [comment]
That's work around looks helpful, thank @lox. I'll give it a try. Also it would be great to make that `script` attribute part of the plugin.

If that works, I'd be happy with it. I'd also be happy with having a `pull` attribute or similar on run to specify additional images to pull before running but I'll start with the workaround.

**Comment by dominics** [comment]
In my case, I just wanted it to pull all containers in the docker-compose before running (so that old already-pulled versions aren't used) - they're all just images, no prebuild interactions. So, I've added [a `pull_all` flag](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/compare/master...vital-software:pull-additional) to my fork (in case someone else is in the same position)

**Comment by lox** [comment]
Implemented in #109.
