### ISSUE TITLE
declare -A breaks plugin on OSX

### ISSUE THREAD

**Issue by toolmantim** [buildkite-plugins/docker-compose-buildkite-plugin#88]
Since `cache-from` support was added in #82 you can no longer use this plugin on OSX’s default Bash, which is version 3.2, because of the addition of `declare -A`.

Perhaps we could remove the use of `declare -A`?

**Comment by lox** [comment]
Argh, that is a real bummer. I would have thought shellcheck would have caught that.

**Comment by dreyks** [comment]
ugh... I even tested this on my Mac setup but since I have up to date bash installed I didn't catch it :/

I'll try to find a workaround

**Comment by dreyks** [comment]
#93

**Comment by toolmantim** [comment]
Closed by #93 - thanks so much @dreyks!
