### ISSUE TITLE
Incorrect parsing of config file strings in 1.8.3 release

### ISSUE THREAD

**Issue by Kiwwa** [buildkite-plugins/docker-compose-buildkite-plugin#99]
After the 1.8.3 release attempts to run the docker-compose-buildkite plugin with multiple config strings has been raising this error (formatted for ease-of-reading);

```
$ docker-compose -f $'docker-compose.yml\ndocker-compose.test.yml' 
  -p buildkiteaaabbcc123123123123 -f docker-compose.buildkite-1430-override.yml 
  run --name buildkiteaaabbcc123123123123_api_build_1430 api bundle exec 
  rake knapsack:rspec

  ERROR: .IOError: [Errno 2] No such file or directory: 
  u'./docker-compose.yml\ndocker-compose.test.yml'
```

The pipeline step throwing this error looks like this;

```  
  - name: ":rspec: %n"
    command: bundle exec rake knapsack:rspec
    parallelism: 8
    plugins:
      docker-compose:
        run: api
        config:
          - docker-compose.yml
          - docker-compose.test.yml
```

Have briefly discussed this with some work colleagues and we believe it is a regression introduced in [this commit](https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/commit/032a6e05bdf00c8951f804d91646b60b8fa12d4b#diff-e0e3e4340eb68e96c2657414fb30f290).

**Comment by lox** [comment]
Thanks for this @Kiwwa and sorry for the regression! I agree that it's almost certainly from that commit.
